# Infrastructure
httpbin_url=https://httpbin.org
wikipedia_url=https://en.wikipedia.org
env=prod
# Browser settings (Carina requirements)
browser=chrome
browser_size=1920x1080
headless=false
# WebDriver configuration
selenium_url=http://localhost:4444/wd/hub
# Reporting & Core config
core_log_level=INFO
demo_mode=false